language: python
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
- sudo dpkg -i hugo*.deb

script:
- hugo

after_script:
- echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
- cd public
- git add .
- git status
- git remote show origin
- git commit -m "commit from travis"
- git push origin master
- cd ..

env:
  global:
  - secure: Sp2MivfAmICDbN+BFzYRA9+o9lDd8bqRmOEm9uRT6tEf2mMJp0FE3xdOH8xkcwri+qLtPXb6Ml3beHcda+Ue2nGior4Qs/uKNo2owptvTWZanh4Ph+X6tILheS3yqhpve2i2T7RgX/Esxm+u+dZFkiaUJAyu74gxmWtE9xrkinU/0Ym6eUhX27stHY0qir8NVJ0TusSLsSpDrC49vjQS6U3C0ypZ2AjzN2HVMaE7cwvp3tfKDCdo0RSNBR0Hkydjx/yqgJ/5MYOi4l32pHu7GxdSazSmRMZeAUiChlQGmb0Kbj/1gvo73RCuAZhigeOcVHmLRJPeEHYqMyTCfzx3A9RmD9xvD/r0wH2lxOLa9yHsjQEB0G8/vTOLFrVVborwei2gDi9ZigN19vQuHbSu5mzL6Pz4zwFTqEDiEErgQraE9kq0o41bLe9pUO37kN0G8hAN2K57jWs0+ClGIymswqAqBjrLG9WvJqRclpqxh78TrPmrrsAq/dm61nw0ACTSou2L5EVSPZvzqxE0j7m2KwJ/U5SSn4boMSelDOANPVrYSr9mnHvrgrD5+PJXsBXTrhvm1IwzK5xhQ62m1qKbI/l1su2PC/ffcu6/Ek2NhdYQdmsuryAMHLfbFJLantISqKRlNrR1DrVJpv0pkHSLDkCTedICAgElP7/R3Gfxp2c=