language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

before_script:
    - git submodule update --init --remote --recursive

script: 
    - hugo

deploy:
  provider: pages
  repo: https://github.com/GenerativeCloth/generativecloth.github.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  target-branch: master
  verbose: true
  on:
    branch: master